pearcej/intro2datasci

source/ch2-identify-data-problems.ptx
=> Unified split paragraph

source/ch1-about-data.ptx
Added code block tags to R code in chapter 1.
I didn't put the character string in a code block because it is already a term. I can do that if it's required.
This fixes issue #23.
I tested my changes locally, and they were reviewed by @Tristan-Raz.
=> Added code block tags to R code

source/ch1-about-data.ptx, source/ch3-r-rstudio-rmarkdown.ptx
Added code tags to "myRange &lt;- range(myFamAge)" in Chapter 3
Fixes issue #25 
I tested it on my local host, and @Tristan-Raz reviewed it.
=> Added code block in Chapter 3

source/ch1-about-data.ptx, source/ch3-r-rstudio-rmarkdown.ptx, source/ch5-rows-and-columns.ptx
Added code blocks to functions and code in the text using "c" and "pre" tags. I added new interactive elements using Sage. I don't know what other elements I should add to the chapter to make it interactive, so any suggestions would be appreciated.
This fixes issue #26.
It was tested locally and was reviewed by @coco3427.
=> Added code blocks to functions and code in the text

source/ch16-line-up-please.ptx
Added idx tags, terms, subsections, fixed grammar, and fixes issue #20 
I added idx tags, terms, a few sections to help readability, fixed grammar/paragraphs, added challenge section, fixes issue #20 
Fixes issue #20 
This has been built locally and reviewed by @coco3427 and @logananglin98
=> Added idx tags, terms, subsections, and fixed grammar for chapter 16

source/ch18-vectors.ptx
Added terms to the index and split up the chapters for readability fixes issue #22
I added some term IDs and bolded terms that needed highlighting. I also split up the major section into many more subsections, the code still needs to be fixed to finish. 
fixes issue#22
It has been built locally and reviewed by @coco3427
=> Added terms to index and split up chapter 18

source/ch1-about-data.ptx, source/ch3-r-rstudio-rmarkdown.ptx, source/ch5-rows-and-columns.ptx, source/ch6-beer-farms-and-peas.ptx
Added the images that were missing in chapter 6 and resized the dropdown-general.png file.
This fixes issue #49.
It was tested locally and was reviewed by @Tristan-Raz and @coco3427
=> Fixing issue #49

source/ch15-map-mashup.ptx
Added tags, terms, subsections, challenges, and images fixes CH 15
I added tags and terms to the index, I added more subsections for readability, I added a challenge section, and added images for chapter 15
fixes issue #19 
I ran a local build and was reviewed by @logananglin98
=> Added tags, terms, subsections, challenges, and images fixes CH 15

source/ch3-r-rstudio-rmarkdown.ptx
Added index terms for chapter 3 along with some minor layout changes and grammar fixes.
Fixes issue #59 
Rebuilding pretext and checking if formatting is correct and ensuring new terms show up in index.
Reviewed by Eun Sung Wang.
=> Issue#59 fix

source/ch7-sample-in-jar.ptx
I turned all of the code segments into pre tags, so that they were readable. I tried making interactive code segments using sage blocks, however a majority of the code segments used external data and functions that i couldn't figure out how to implement. I had Elijah help me and we both came to the conclusion that pre tags were the best option.
fixes issue #28
built and viewed by Elijah.
=> FIxed broken code segments in Ch 7

source/ch7-sample-in-jar.ptx
I put all key terms I could find into term tags, and indexed them. I did make a term out of the quantile() and sample() functions in r as they are used in the text extensively and important to the content of the chapter.
fixes issue #11 
I tested this by building it and viewing it locally. I had @Austing767 review it and he helped me find a term i missed.
=> fixes issue #11. Adds key terms and indexes them

source/ch11-popularity-contest.ptx
Changed file names for non-working images.
The image names were not correct; I changed them to the correct image file names.
fixes issue #82 
Ran and built locally.
=> Added correct image file name, fixes issue #82

source/ch11-popularity-contest.ptx
The code in this section was not formatted and was hard to read. So I changed it to active code.
While I did change the symbols to their alt text versions so it could compile, it does return the function and seems to work, so we could add a note at the bottom to add their own data and manipulate it, or some kind of exercise, but that is a different issue. 
Fixes issue #80 
Note that the code testing is not present in the PR; this was for my testing.
Ran and built locally
No peer review finished at 4:58 pm Central Time
=>  I changed the format to active code, fixes issue #80

source/ch6-beer-farms-and-peas.ptx
Added sage cells, code blocks, and pre tags to Chapter 6.
This fixes issue #27.
I tested it locally, and @coco3427 reviewed it.
=> Added sage cells, code blocks, and pre tags to Chapter 6

source/ch5-rows-and-columns.ptx
This pull request is a replacement for pull request #73. I ensured this one only adds idx tags to chapter 5 without changing anything else.
Fixes issue #9.
Building the book and ensuring the terms show up in the index.
Reviewed by Elijah Babayemi and Colin Flaherty.
=> Added Index Terms to Chapter 5 without changing image names.

source/ch13-word-perfect.ptx
Adds in subsections and fixes the translation errors with paragraphs.
I added subsections, sections, and fixed the paragraphs from the translation, starting a new line mid-sentence.
Fixes issue #113 
It has been built locally and reviewed by @logananglin98
=> Adds in subsections and fixes the paragraphs fixes issue #113

source/ch9-onward-with-rstudio.ptx
Added missing images back into chapter 9
This fixes issue #76.
It was tested locally, and it was reviewed by @coco3427.
=> Added missing images back into chapter 9

source/ch9-onward-with-rstudio.ptx
Added index terms for chapter 9 and made minor layout changes.
Fixes issue #13.
Building the book and ensuring the terms show up in the index.
Reviewed by Austin Gatewood, Colin Flaherty, and Eun Sung Wang.
=> Added index terms for chapter 9 

source/ch4-follow-the-data.ptx
Solving Issue #96 
I have just added the decorative tag to the image, and I believe it does not need any description to it.
Reviewed by Tristan and Austin
=> Adding decorative tag to the Image

source/ch5-rows-and-columns.ptx
Solving Issue #97 
There are no description needed to added in this Chapter, but there was an image was missing a decorative tag, so I have added that instead.
=> Adding decorative tag on image in Chapter 5

code/delay-probability.r, source/ch11-popularity-contest.ptx
I have added the base code for others to use in this PR, as well as the code folder for the code and data set
This PR adds the code needed to import R code from a file. I have added a folder called code.
Will add a second PR for the database, xlsx file.
Built and viewed locally
Reviewed by everyone
=> Added the base xi:include statement, as well as code folder

source/ch12-string-theory.ptx, source/ch8-big-data-big-deal.ptx
Adds a decorative image to chapter 8 and sections off chapter 12 while fixing translator errors.
Adds an image for decoration at the beginning of chapter 8 and has an accessibility caption built in.
I sectioned off chapter 12 to help the students digest the material more easily and fixed the paragraphs, stopping mid-sentence. 
Fixes issue #129 and fixes issue #118
This has been built locally and reviewed by @coco3427
=> Fixing ch8 issue129 and fixes ch12 issue#118

source/ch12-string-theory.ptx
Added image descriptions and deleted duplicate text in chapter 12.1.
This fixes issue #102.
I tested it locally, and it was reviewed by @Tristan-Raz.
=> Fixing issue #102

source/ch14-storage-wars.ptx
Adds key terms and indexes them, fixes issue #133
I read through the chapter and added term highlights and indexed any highlighted terms so that students can look them up more easily.
Fixes issue #133 
This has been built locally and reviewed by @FlashEb and @esw0624
=> Adds key terms and indexes them fixes issue #133

source/ch2-identify-data-problems.ptx
Breaks up the long text into shorter digestable sections fixes issue Ch2
I broke up the long text into smaller sections and subsections to help readability. 
Fixes issue #139 
=> Breaks up the long text into shorter digestable sections fixes issue Ch2

source/ch11-popularity-contest.ptx
Resolving Issue #101 
I have added missing image or figure's description or caption. And also I do not know if anybody added an issue on a missing image on Chapter 11, but I have found that it was missing a decorative image, so I have also added it into this pull request.
Reviewed by Tristan & Logan
=> Adding image description and also adding missing decorative image in Chapter 11

source/ch9-onward-with-rstudio.ptx
Adds a section and subsection to help readability fixes issue #151
Adds a section and subsection to help readability 
fixes issue #151
=> Adds a section and subsection to help readability fixes issue #151

source/ch10-tweet-tweet.ptx, source/ch11-popularity-contest.ptx, source/ch12-string-theory.ptx, source/ch13-word-perfect.ptx, source/ch14-storage-wars.ptx, source/ch15-map-mashup.ptx, source/ch16-line-up-please.ptx, source/ch17-data-mining.ptx, source/ch18-vectors.ptx, source/ch8-big-data-big-deal.ptx, source/ch9-onward-with-rstudio.ptx
Changes subsection tags to section tags fixes issue #168
I replaced subsection tags to section tags from chapters 8-18 to help the numbering of sections.
fixes issue #168 
This has been built locally and reviewed by @logananglin98 and @coco3427
=> Changes subsection tags to section tags fixes issue #168

source/ch11-popularity-contest.ptx
Adds sections to enhance readability fixes issue #174
Adds sections to enhance readability for chapter 11 and breaks apart the reading. 
fixes issue #174
This has been built locally and reviewed by @coco3427 and @FlashEb
=> Adds sections to enhance readability fixes issue #174

source/ch6-beer-farms-and-peas.ptx
I have added a Sage code block that runs USstatePops in chapter 6.
Fixes issue #26 
Ran and pair programed with @coco3427
=> Fixes issue #26, adds code block to run USstatePops in chapter 6

source/ch7-sample-in-jar.ptx
Adds sections to help readability, fixes issue #172
Adds sections to help readability and break up sections.
fixes issue #172 
This has been built by @coco3427 and @FlashEb
=> Adds sections to help readability fixes issue #172

source/ch10-tweet-tweet.ptx, source/ch11-popularity-contest.ptx, source/ch13-word-perfect.ptx, source/ch15-map-mashup.ptx, source/ch16-line-up-please.ptx, source/ch17-data-mining.ptx, source/ch18-vectors.ptx, source/ch6-beer-farms-and-peas.ptx, source/ch7-sample-in-jar.ptx, source/frontmatter.ptx
=> Remove Sources sections

source/ch4-follow-the-data.ptx
Adds a test yourself question to fix issue #197
Adds a test yourself question to fix issue #197
fixes issue #197 
=> Adds a test yourself question to fix issue #197

source/ch2-identify-data-problems.ptx
Adds a test yourself section, fixes issue #196
Adds a test yourself section,n fixes issue #196
fixes issue #196 
This has been built locally and reviewed by @Austing767 and @logananglin98
=> Adds a test yourself section fixes issue #196

source/ch9-onward-with-rstudio.ptx
Adds two intro questions to chapter 9 fixes issue #203
Adds two intro questions to chapter 9 in case it is moved.
fixes issue #203
This has been reviewed by @logananglin98 and built locally
=> Adds two intro questions to chapter 9 fixes issue #203

source/ch5-rows-and-columns.ptx
Adds two test yourself question and moves chapter challenge 
Adds two test yourself question and moves chapter challenge 
Fixes issue #199
This has been reviewed by @logananglin98 and built locally
=> Adds two test yourself question and moves chapter challenge 

code/afl-attendance.r, source/ch16-line-up-please.ptx
I added an r file that downloads the dataset, and used that to make all of the sage cells functional.  I also put code that was used as examples in pre tags so it was consolidated and readable.
fixes issue #36 
I built and ran it and had @Austing767 and @Tristan-Raz
=> fixes issue #36 Adding code bocks and pre tags

source/ch6-beer-farms-and-peas.ptx
Formats chapter 6 and adds test yourself fixes issue #200
Formats chapter 6 and adds test yourself 
fixes issue #200
This has been built locally and reviewed by @coco3427
=> Formats chapter 6 and adds test yourself fixes issue #200

source/ch7-sample-in-jar.ptx
Adds three questions and moves the chapter challenge fixes issue #201
Adds three questions and moves the chapter challenge 
fixes issue #201
=> Adds three questions and moves the chapter challenge fixes issue #201

source/ch8-big-data-big-deal.ptx
I have added two multiple-choice questions in Chapter 8 and made changes to Test Yourself. The questions are about ease of accessibility and garbage in and garbage out, both found in chapter 8.1.
Fixes issue #202 
Ran and viewed locally, checked by @Tristan-Raz
=> Added 2 MC questions, fixes issue #202

source/ch16-line-up-please.ptx
Adds three questions related to the knowledge and moves the challenge questions.
fixes issue #205
=> Adds three questions fixes issue #205

source/ch10-tweet-tweet.ptx
Solving Issue #230 
It is just a simple visual issue, which I removed the figure tag which the image does not need it as it is a decorative image, and I have added the description in the <em> element.
=> Removing figure tag and adding <em> element to its description

source/ch9-onward-with-rstudio.ptx
I fixed a few issues with syntax errors in the code.  I tried to figure out why the exercise section has so many errors, but after a few ours i moved on. according to my reading of the pretext guide that section is formatting write, and I even tried copying and pasting a question section from another book to check and it gave the same errors for it as well.
issue #232 
I built and tested it locally, and had @FlashEb check it out
=> fixes syntax errors in chapter 9

source/ch14-storage-wars.ptx
Updated information in 14.3 that was outdated.
This partially addresses issue #155. I'll check it to see if there is more outdated information.
This was tested locally and reviewed by @coco3427
=> Information in Chapter 14.3 is now updated

code/ai_job_dataset.r
Added file needed for ch 13 and 14 to import the ai_job_dataset. I need pulled so logan can work on 13 while i work on 12,
I built and ran it and tested the sage cells.
=> added r file that imports the ai_job_dataset

source/ch8-big-data-big-deal.ptx
Resolves Issue #248 
I have removed the figure tag for the image used in this section as it is a decorative image and I have also added the em element to the chapter's description aligning and following with the Google Doc Book.
=> Removed figure tag and added <em> element to its description

source/ch9-onward-with-rstudio.ptx
Added the method for the mfv function for it to work, and added an explanation that the whole method does not have to be run when running it.
This fixes issue #193.
This was tested locally and reviewed by @Tristan-Raz.
=> Added the method for the mfv function for it to work
